name: Validate changelog entries
on: [push, pull_request]
jobs:
  validate-changelog:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: validate changelogs
      uses: thiagodnf/yaml-schema-checker@v0.0.8
      with:
        jsonSchemaFile: changelog/schema/schema.json
        yamlFiles: |
          changelog/kong/*.yaml
          changelog/kong-ee/*.yaml
